# Generated by Django 5.0 on 2024-01-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
