# Generated by Django 5.0 on 2024-01-07 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_entry_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='password',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(50, 'Password must contain atleast 8 characters')]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
