# Generated by Django 5.0 on 2024-01-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_entry_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
